package lk.vexview.event;

public enum MinecraftKeys {

    KEY_NONE(new int[]{0}),
    KEY_ESC(new int[]{1}),
    KEY_1(new int[]{2}),
    KEY_2(new int[]{3}),
    KEY_3(new int[]{4}),
    KEY_4(new int[]{5}),
    KEY_5(new int[]{6}),
    KEY_6(new int[]{7}),
    KEY_7(new int[]{8}),
    KEY_8(new int[]{9}),
    KEY_9(new int[]{10}),
    KEY_0(new int[]{11}),
    KEY_MINUS(new int[]{12}),
    KEY_EQUALS(new int[]{13}),
    KEY_BACKSPACE(new int[]{14}),
    KEY_TAB(new int[]{15}),
    KEY_Q(new int[]{16}),
    KEY_W(new int[]{17}),
    KEY_E(new int[]{18}),
    KEY_R(new int[]{19}),
    KEY_T(new int[]{20}),
    KEY_Y(new int[]{21}),
    KEY_U(new int[]{22}),
    KEY_I(new int[]{23}),
    KEY_O(new int[]{24}),
    KEY_P(new int[]{25}),
    KEY_LBRACKET(new int[]{26}),
    KEY_RBRACKET(new int[]{27}),
    KEY_ENTER(new int[]{28}),
    KEY_LEFT_CTRL(new int[]{29}),
    KEY_A(new int[]{30}),
    KEY_S(new int[]{31}),
    KEY_D(new int[]{32}),
    KEY_F(new int[]{33}),
    KEY_G(new int[]{34}),
    KEY_H(new int[]{35}),
    KEY_J(new int[]{36}),
    KEY_K(new int[]{37}),
    KEY_L(new int[]{38}),
    KEY_SEMICOLON(new int[]{39}),
    KEY_APOSTROPHE(new int[]{40}),
    KEY_GRAVE(new int[]{41}),
    KEY_LEFT_SHIFT(new int[]{42}),
    KEY_BACKSLASH(new int[]{43}),
    KEY_Z(new int[]{44}),
    KEY_X(new int[]{45}),
    KEY_C(new int[]{46}),
    KEY_V(new int[]{47}),
    KEY_B(new int[]{48}),
    KEY_N(new int[]{49}),
    KEY_M(new int[]{50}),
    KEY_COMMA(new int[]{51}),
    KEY_PERIOD(new int[]{52}),
    KEY_SLASH(new int[]{53}),
    KEY_RIGHT_SHIFT(new int[]{54}),
    KEY_MULTIPLY(new int[]{55}),
    KEY_LEFT_ALT(new int[]{56}),
    KEY_SPACE(new int[]{57}),
    KEY_CAPS_LOCK(new int[]{58}),
    KEY_F1(new int[]{59}),
    KEY_F2(new int[]{60}),
    KEY_F3(new int[]{61}),
    KEY_F4(new int[]{62}),
    KEY_F5(new int[]{63}),
    KEY_F6(new int[]{64}),
    KEY_F7(new int[]{65}),
    KEY_F8(new int[]{66}),
    KEY_F9(new int[]{67}),
    KEY_F10(new int[]{68}),
    KEY_NUM_LOCK(new int[]{69, 325}),
    KEY_SCROLL(new int[]{70}),
    KEY_NUMPAD7(new int[]{71}),
    KEY_NUMPAD8(new int[]{72}),
    KEY_NUMPAD9(new int[]{73}),
    KEY_SUBTRACT(new int[]{74}),
    KEY_NUMPAD4(new int[]{75}),
    KEY_NUMPAD5(new int[]{76}),
    KEY_NUMPAD6(new int[]{77}),
    KEY_ADD(new int[]{78}),
    KEY_NUMPAD1(new int[]{79}),
    KEY_NUMPAD2(new int[]{80}),
    KEY_NUMPAD3(new int[]{81}),
    KEY_NUMPAD0(new int[]{82}),
    KEY_DECIMAL(new int[]{83}),
    KEY_F11(new int[]{87}),
    KEY_F12(new int[]{88}),
    KEY_F13(new int[]{100}),
    KEY_F14(new int[]{101}),
    KEY_F15(new int[]{102}),
    KEY_F16(new int[]{103}),
    KEY_F17(new int[]{104}),
    KEY_F18(new int[]{105}),
    KEY_KANA(new int[]{112}),
    KEY_F19(new int[]{113}),
    KEY_CONVERT(new int[]{121}),
    KEY_NOCONVERT(new int[]{123}),
    KEY_YEN(new int[]{125}),
    KEY_NUMPADEQUALS(new int[]{141}),
    KEY_CIRCUMFLEX(new int[]{144}),
    KEY_AT(new int[]{145}),
    KEY_COLON(new int[]{146}),
    KEY_UNDERLINE(new int[]{147}),
    KEY_KANJI(new int[]{148}),
    KEY_STOP(new int[]{149}),
    KEY_AX(new int[]{150}),
    KEY_UNLABELED(new int[]{151}),
    KEY_NUMPAD_ENTER(new int[]{156, 284}),
    KEY_RIGHT_CTRL(new int[]{157, 285}),
    KEY_SECTION(new int[]{167}),
    KEY_NUMPAD_COMMA(new int[]{179}),
    KEY_DIVIDE(new int[]{181, 309}),
    KEY_SYSRQ(new int[]{183, 311}),
    KEY_RIGHT_ALT(new int[]{184, 312}),
    KEY_FUNCTION(new int[]{196}),
    KEY_PAUSE(new int[]{197, 69}),
    KEY_HOME(new int[]{199, 327}),
    KEY_UP(new int[]{200, 328}),
    KEY_PAGE_UP(new int[]{201, 329}),
    KEY_LEFT(new int[]{203, 331}),
    KEY_RIGHT(new int[]{205, 333}),
    KEY_END(new int[]{207, 335}),
    KEY_DOWN(new int[]{208, 336}),
    KEY_PAGE_DOWN(new int[]{209, 337}),
    KEY_INSERT(new int[]{210}),
    KEY_DELETE(new int[]{211, 339}),
    KEY_CLEAR(new int[]{218}),
    KEY_LEFT_WIN(new int[]{219, 347}),
    KEY_RIGHT_MENU(new int[]{220, 349}),
    KEY_APPS(new int[]{221}),
    KEY_POWER(new int[]{222}),
    KEY_SLEEP(new int[]{223});

    int[] key;

    private MinecraftKeys(int... key) {
        this.key = key;
    }

    public boolean isTheKey(int k) {
        int[] var2 = this.key;
        int var3 = var2.length;

        for(int var4 = 0; var4 < var3; ++var4) {
            int kx = var2[var4];
            if (kx == k) {
                return true;
            }
        }

        return false;
    }

}
